# For local testing use this: https://github.com/nektos/act

name: PR Test Runner

on:
  pull_request:
    types: [ opened, synchronize, reopened ] # default events - listed to make them explicit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
          java-package: jdk
          architecture: x64
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
      - name: Gradle test execution
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 7.1
          arguments: test